package edu.eci.arep.roundRobin.front;

public class Front {
	
	public static final String HTML = ""
			+ "<!DOCTYPE html>\r\n"
			+ "<html>\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "	<meta charset=\"utf-8\">\r\n"
			+ "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "	<title>ECI | Math Services</title>\r\n"
			+ "	<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n"
			+ "	<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js\"></script>\r\n"
			+ "	<script type=\"text/javascript\">\r\n"
			+ "		var pageApi = (function() {\r\n"
			+ "\r\n"
			+ "			var _num = \"\";\r\n"
			+ "\r\n"
			+ "			function _getTimeAndDate() {\r\n"
			+ "				let currentDate = \"\";\r\n"
			+ "				var today = new Date();\r\n"
			+ "				currentDate = today.getDate()+\"/\"+(today.getMonth()+1)+\"/\"+today.getFullYear()+\" - \"+\r\n"
			+ "							  today.getHours()+\":\"+today.getMinutes()+\":\"+today.getSeconds();\r\n"
			+ "				return currentDate;\r\n"
			+ "			}\r\n"
			+ "\r\n"
			+ "			function _isValidNumber(service) {\r\n"
			+ "				let isValid = false;\r\n"
			+ "				let string = $(\"#\"+service+\"Number\").val();\r\n"
			+ "				if (!( string === \"\" || string == null )) {\r\n"
			+ "					isValid = true;\r\n"
			+ "					_num = string;\r\n"
			+ "				}\r\n"
			+ "				return isValid;\r\n"
			+ "			}\r\n"
			+ "\r\n"
			+ "			function _getSqrt() {\r\n"
			+ "				console.log(\"IN GET SQRT: \"+_num);\r\n"
			+ "				var getPromise = $.get(\"/sqrt?value=\"+_num);\r\n"
			+ "				getPromise.then(\r\n"
			+ "					function(data) {\r\n"
			+ "						console.log(\"Done! (Sqrt)\");\r\n"
			+ "						var obj = JSON.parse(JSON.stringify(data));\r\n"
			+ "						console.log(\"  Data: \"+JSON.stringify(data)+\"\\n\");\r\n"
			+ "						window.alert(\r\n"
			+ "							\"Operation: \"+obj.operation+\"\\n\"+\r\n"
			+ "							\"Input: \"+obj.input+\"\\n\"+\r\n"
			+ "							\"Output: \"+obj.output\r\n"
			+ "						);\r\n"
			+ "					},\r\n"
			+ "					function(data) {\r\n"
			+ "						console.log(\"Error! (Sqrt)\");\r\n"
			+ "						console.log(\"  Data: \"+JSON.stringify(data)+\"\\n\");\r\n"
			+ "					}\r\n"
			+ "				);\r\n"
			+ "			}\r\n"
			+ "\r\n"
			+ "			function _getExp() {\r\n"
			+ "				console.log(\"IN GET EXP: \"+_num);\r\n"
			+ "				var getPromise = $.get(\"/exp?value=\"+_num);\r\n"
			+ "				getPromise.then(\r\n"
			+ "					function(data) {\r\n"
			+ "						console.log(\"Done! (Exp)\");\r\n"
			+ "						var obj = JSON.parse(JSON.stringify(data));\r\n"
			+ "						console.log(\"  Data: \"+JSON.stringify(data)+\"\\n\");\r\n"
			+ "						window.alert(\r\n"
			+ "							\"Operation: \"+obj.operation+\"\\n\"+\r\n"
			+ "							\"Input: \"+obj.input+\"\\n\"+\r\n"
			+ "							\"Output: \"+obj.output\r\n"
			+ "						);\r\n"
			+ "					},\r\n"
			+ "					function(data) {\r\n"
			+ "						console.log(\"Error! (Exp)\");\r\n"
			+ "						console.log(\"  Data: \"+JSON.stringify(data));\r\n"
			+ "					}\r\n"
			+ "				);\r\n"
			+ "			}\r\n"
			+ "\r\n"
			+ "			function calculateSqrt() {\r\n"
			+ "				if (_isValidNumber(\"sqrt\")) {\r\n"
			+ "					console.log(\"Send at: \"+_getTimeAndDate());\r\n"
			+ "					_getSqrt();\r\n"
			+ "				}\r\n"
			+ "				else {\r\n"
			+ "					window.alert(\"The 'Number' field cannot be empty\");\r\n"
			+ "				}\r\n"
			+ "			}\r\n"
			+ "\r\n"
			+ "			function calculateExp() {\r\n"
			+ "				if (_isValidNumber(\"exp\")) {\r\n"
			+ "					console.log(\"Send at: \"+_getTimeAndDate());\r\n"
			+ "					_getExp();\r\n"
			+ "				}\r\n"
			+ "				else {\r\n"
			+ "					window.alert(\"The 'Number' field cannot be empty\");\r\n"
			+ "				}\r\n"
			+ "			}\r\n"
			+ "\r\n"
			+ "			return {\r\n"
			+ "				calculateSqrt: calculateSqrt,\r\n"
			+ "				calculateExp: calculateExp\r\n"
			+ "			}\r\n"
			+ "		})();\r\n"
			+ "	</script>\r\n"
			+ "	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\">\r\n"
			+ "	<style type=\"text/css\">\r\n"
			+ "		body {\r\n"
			+ "			background-image: linear-gradient(to right bottom, #051937, #003b5e, #00607c, #00868d, #07ac8f);\r\n"
			+ "		}\r\n"
			+ "		* {\r\n"
			+ "			Font-family: Century Gothic, CenturyGothic, AppleGothic, sans-serif;\r\n"
			+ "		}\r\n"
			+ "		html, body {\r\n"
			+ "			height: 100%;\r\n"
			+ "			width: 100%;\r\n"
			+ "			padding: 0%;\r\n"
			+ "			margin: 0%;\r\n"
			+ "			font-size: 100%;\r\n"
			+ "		}\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "		.titleText {\r\n"
			+ "			text-align: center;\r\n"
			+ "			color: white;\r\n"
			+ "		}\r\n"
			+ "		#header {\r\n"
			+ "			width: 100%;\r\n"
			+ "			padding: 1rem 0rem 1rem 0rem;\r\n"
			+ "			background-color: black;\r\n"
			+ "		}\r\n"
			+ "		input {\r\n"
			+ "			margin-top: 0.8rem;\r\n"
			+ "			font-size: 1.5rem;\r\n"
			+ "			text-align: center;\r\n"
			+ "			border-radius: 5px;\r\n"
			+ "			padding-top: 0.4rem;\r\n"
			+ "			padding-bottom: 0.4rem;\r\n"
			+ "			width: 20%;\r\n"
			+ "		}\r\n"
			+ "		button {\r\n"
			+ "			background-color: #390071;\r\n"
			+ "			border-radius: 5px;\r\n"
			+ "			color: white;\r\n"
			+ "			margin-top: 0.5rem;\r\n"
			+ "			margin-bottom: 1rem;\r\n"
			+ "			font-size: 1.2rem;\r\n"
			+ "			font-weight: bolder;\r\n"
			+ "			border:  none;\r\n"
			+ "			padding: 0.4rem 1.2rem 0.4rem 1.2rem;\r\n"
			+ "			transition: 0.5s;\r\n"
			+ "		}\r\n"
			+ "		button:hover {\r\n"
			+ "			transform: scale(1.1);\r\n"
			+ "		}\r\n"
			+ "		table {\r\n"
			+ "			border-collapse: collapse;\r\n"
			+ "			margin-left: auto;\r\n"
			+ "			margin-right: auto;\r\n"
			+ "			width: 33%;\r\n"
			+ "		}\r\n"
			+ "		th {\r\n"
			+ "		    font-weight: bold;\r\n"
			+ "		    background-color: #390071;\r\n"
			+ "		    color: white;\r\n"
			+ "			padding-top: 0.3rem;\r\n"
			+ "			padding-bottom: 0.3rem;\r\n"
			+ "		}\r\n"
			+ "		th, td {\r\n"
			+ "		    text-align: center;\r\n"
			+ "		    border: 1px solid #646464;\r\n"
			+ "		}\r\n"
			+ "		td {\r\n"
			+ "			background-color: black;\r\n"
			+ "			color: white;\r\n"
			+ "		}\r\n"
			+ "	</style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "	<p class=\"titleText\" id=\"header\" style=\"font-size: 2rem;\">\r\n"
			+ "		ECI MATH SERVICES<br>\r\n"
			+ "	</p>\r\n"
			+ "	<p class=\"titleText\" style=\"font-size: 1.5rem;\">\r\n"
			+ "		SQRT FUNCTION<br>\r\n"
			+ "		Type a real number:<br>\r\n"
			+ "		<input id=\"sqrtNumber\" type=\"text\" placeholder=\"Your Number\"><br>\r\n"
			+ "		<button id=\"sendBtn\" onclick=\"pageApi.calculateSqrt()\">CALCULATE</button>\r\n"
			+ "	</p>\r\n"
			+ "	<p class=\"titleText\" style=\"font-size: 1.5rem;\">\r\n"
			+ "		EXP FUNCTION<br>\r\n"
			+ "		Type a real number:<br>\r\n"
			+ "		<input id=\"expNumber\" type=\"text\" placeholder=\"Your Number\"><br>\r\n"
			+ "		<button id=\"sendBtn\" onclick=\"pageApi.calculateExp()\">CALCULATE</button>\r\n"
			+ "	</p>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>";
}