package edu.eci.arep.roundRobin.front;

public class Front {
	
	private static final String CSS = ""
			+ "body {\r\n"
			+ "	background-image: linear-gradient(to right bottom, #051937, #003b5e, #00607c, #00868d, #07ac8f);\r\n"
			+ "}\r\n"
			+ "* {\r\n"
			+ "	Font-family: Century Gothic, CenturyGothic, AppleGothic, sans-serif;\r\n"
			+ "}\r\n"
			+ "html, body {\r\n"
			+ "	height: 100%;\r\n"
			+ "	width: 100%;\r\n"
			+ "	padding: 0%;\r\n"
			+ "	margin: 0%;\r\n"
			+ "	font-size: 100%;\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "\r\n"
			+ ".titleText {\r\n"
			+ "	text-align: center;\r\n"
			+ "	color: white;\r\n"
			+ "}\r\n"
			+ "#header {\r\n"
			+ "	width: 100%;\r\n"
			+ "	padding: 1rem 0rem 1rem 0rem;\r\n"
			+ "	background-color: black;\r\n"
			+ "}\r\n"
			+ "input {\r\n"
			+ "	margin-top: 0.8rem;\r\n"
			+ "	font-size: 1.5rem;\r\n"
			+ "	text-align: center;\r\n"
			+ "	border-radius: 5px;\r\n"
			+ "	padding-top: 0.4rem;\r\n"
			+ "	padding-bottom: 0.4rem;\r\n"
			+ "	width: 20%;\r\n"
			+ "}\r\n"
			+ "button {\r\n"
			+ "	background-color: #390071;\r\n"
			+ "	border-radius: 5px;\r\n"
			+ "	color: white;\r\n"
			+ "	margin-top: 0.5rem;\r\n"
			+ "	margin-bottom: 1rem;\r\n"
			+ "	font-size: 1.2rem;\r\n"
			+ "	font-weight: bolder;\r\n"
			+ "	border:  none;\r\n"
			+ "	padding: 0.4rem 1.2rem 0.4rem 1.2rem;\r\n"
			+ "	transition: 0.5s;\r\n"
			+ "}\r\n"
			+ "button:hover {\r\n"
			+ "	transform: scale(1.1);\r\n"
			+ "}\r\n"
			+ "table {\r\n"
			+ "	border-collapse: collapse;\r\n"
			+ "	margin-left: auto;\r\n"
			+ "	margin-right: auto;\r\n"
			+ "	width: 33%;\r\n"
			+ "}\r\n"
			+ "th {\r\n"
			+ "    font-weight: bold;\r\n"
			+ "    background-color: #390071;\r\n"
			+ "    color: white;\r\n"
			+ "	padding-top: 0.3rem;\r\n"
			+ "	padding-bottom: 0.3rem;\r\n"
			+ "}\r\n"
			+ "th, td {\r\n"
			+ "    text-align: center;\r\n"
			+ "    border: 1px solid #646464;\r\n"
			+ "}\r\n"
			+ "td {\r\n"
			+ "	background-color: black;\r\n"
			+ "	color: white;\r\n"
			+ "}";
	
	private static final String JS = ""
			+ "var pageApi = (function() {\r\n"
			+ "\r\n"
			+ "	var _str = \"\";\r\n"
			+ "\r\n"
			+ "	function _getTimeAndDate() {\r\n"
			+ "		let currentDate = \"\";\r\n"
			+ "		var today = new Date();\r\n"
			+ "		currentDate = today.getDate()+\"/\"+(today.getMonth()+1)+\"/\"+today.getFullYear()+\" - \"+\r\n"
			+ "					  today.getHours()+\":\"+today.getMinutes()+\":\"+today.getSeconds();\r\n"
			+ "		return currentDate;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	function _isValidString() {\r\n"
			+ "		let isValid = false;\r\n"
			+ "		let string = $(\"#inputString\").val();\r\n"
			+ "		if (!( string === \"\" || string == null )) {\r\n"
			+ "			isValid = true;\r\n"
			+ "			_str = string;\r\n"
			+ "		}\r\n"
			+ "		return isValid;\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	function _saveString() {\r\n"
			+ "		console.log(\"IN GET: \"+_str);\r\n"
			+ "		var getPromise = $.get(\"/saveString/\"+_str);\r\n"
			+ "		getPromise.then(\r\n"
			+ "			function(data) {\r\n"
			+ "				console.log(\"Done!\");\r\n"
			+ "				console.log(\"  Data: \"+JSON.stringify(data));\r\n"
			+ "			},\r\n"
			+ "			function(data) {\r\n"
			+ "				console.log(\"Error!\");\r\n"
			+ "				console.log(\"  Data: \"+JSON.stringify(data));\r\n"
			+ "			}\r\n"
			+ "		);\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	function saveString() {\r\n"
			+ "		if (_isValidString()) {\r\n"
			+ "			console.log(\"Send at: \"+_getTimeAndDate());\r\n"
			+ "			_saveString();\r\n"
			+ "		}\r\n"
			+ "		else {\r\n"
			+ "			window.alert(\"The 'String' field cannot be empty\");\r\n"
			+ "		}\r\n"
			+ "	}\r\n"
			+ "\r\n"
			+ "	return {\r\n"
			+ "		saveString: saveString\r\n"
			+ "	}\r\n"
			+ "})();";
	
	public static final String HTML = ""
			+ "<!DOCTYPE html>\r\n"
			+ "<html>\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "	<meta charset=\"utf-8\">\r\n"
			+ "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "	<title>ECI | containers Services</title>\r\n"
			+ "	<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n"
			+ "<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js\"></script>"
			+ "	<script type=\"text/javascript\">\r\n"
			+		JS
			+ "	</script>\r\n"
			+ "<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\">"
			+ "	<style type=\"text/css\">\r\n"
			+ 		CSS
			+ "	</style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "	<p class=\"titleText\" id=\"header\" style=\"font-size: 2rem;\">\r\n"
			+ "		ECI SERVICES<br>\r\n"
			+ "		WEBSERVER & MONGODB IN CONTAINERS FOR AWS\r\n"
			+ "	</p>\r\n"
			+ "	<p class=\"titleText\" style=\"font-size: 1.5rem;\">\r\n"
			+ "		Type a String<br>\r\n"
			+ "		<input id=\"inputString\" type=\"text\" placeholder=\"Anything\"><br>\r\n"
			+ "		<button id=\"sendBtn\" onclick=\"pageApi.saveString()\">SEND</button>\r\n"
			+ "	</p>\r\n"
			+ "	<p class=\"titleText\" id=\"tableTitle\" style=\"font-size: 1.5rem;\">Last Stored Strings</p>\r\n"
			+ "	<p class=\"titleText\">\r\n"
			+ "		<table>\r\n"
			+ "			<tr>\r\n"
			+ "				<th>STRING</th>\r\n"
			+ "				<th>DATE</th>\r\n"
			+ "			</tr>\r\n"
			+ "			<tbody>\r\n"
			+ "				<!-- FIlled by js -->\r\n"
			+ "				<tr>\r\n"
			+ "					<td>fsefsefsefse</td>\r\n"
			+ "					<td>01/01/2022</td>\r\n"
			+ "				</tr>\r\n"
			+ "			</tbody>\r\n"
			+ "		</table>\r\n"
			+ "	</p>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>";
	
}